### PR TITLE
build: use rollup, add es module bundle

### PR DESCRIPTION
**Pull request by giannif**
This PR uses [rollup](https://rollupjs.org) to create a few builds optimized for node and for the browser. 

- `lib/` contains a cjs build for node
- `dist/` contains umd builds for the browser and an es module build for compilers that support the module field 

It also reduces the size substantially when bundling.

Here's the original:

screen shot 2017-10-22 at 8 28 03 am

This build is 10k smaller gzipped. 

One thing to mention is that I removed the [core-js polyfill](https://github.com/patriciogonzalezvivo/glslCanvas/blob/master/build/GlslCanvas.js#L1) since the code base doesn't use any of the features (`Promise`, `Set`, `Map` etc.).

If you need one of these polyfills, the approach I see most libs take is tell the user they may need a polyfill if they want to support an older browser (e.g. [unfetch](https://github.com/developit/unfetch#unfetch) says include the Promise polyfill to support IE 8).

### CODE REVIEW

**Comment by giannif** [comment]
@patriciogonzalezvivo I updated the description here, the first one was a bit convoluted.

**Comment by patriciogonzalezvivo** [comment]
Thanks for this big effort. Hope doesn’t break think

**Comment by giannif** [comment]
@patriciogonzalezvivo we've used this build in production, if that's any reassurance. 

The rawgit link changed from `build` to `dist`, and I update the README.md, but existing links may break. It's not best practice to rely on rawgit links anyway, I don't think. 

Do you plan on `npm` publishing soon?

**Comment by patriciogonzalezvivo** [comment]
Hi @RoryO @giannif I'm trying to re build in yarn and I'm getting this:

```
[~/Desktop/glslCanvas]$ yarn run build                                                                                                               *[master] 
yarn run v1.3.2
$ rollup -c

src/GlslCanvas.js → lib/GlslCanvas.js...
[!] (babel plugin) Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
src/GlslCanvas.js
Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at error (/Users/patricio/Desktop/glslCanvas/node_modules/rollup/dist/rollup.js:185:14)
    at Object.error (/Users/patricio/Desktop/glslCanvas/node_modules/rollup/dist/rollup.js:9469:6)
    at promise.then.previous (/Users/patricio/Desktop/glslCanvas/node_modules/rollup/dist/rollup.js:9478:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any ideas?

**Comment by giannif** [comment]
@patriciogonzalezvivo when you ran `yarn` with an empty `node_modules` directory, `babel-env` overwrote the `.babelrc`. Have never seen it do that before, luckily there's a way to disable it. 

Checkout the `.babelrc` and add a comment to the top line:

```javascript
// babel-env-disable
{
    "presets": [
        [
            "env",
            {
                "modules": false,
                "targets": {
                    "browsers": ["last 2 versions", "ie 10"]
                }
            }
        ]
    ],
    "plugins": ["external-helpers"]
}
```

**Comment by RoryO** [comment]
@giannif perhaps put the babel config in `package.json` instead?

**Comment by giannif** [comment]
@patriciogonzalezvivo  `dist` is for the browser and contains a UMD build, it's what's used if you're not using `GlslCanvas` as a dependency. It can be loaded directly in the browser. There's also the minified version `dist/GlslCanvas.min.js`.`

`lib` is what's referenced in the package.json `"main": "lib/GlslCanvas.js"`, and when you use a module bundler like Webpack, that's what is used. It's CJS format, the format for node. However, bundlers can also use the more modern `es` format, and so in the package.json you also see `module": "dist/GlslCanvas.es.js"`. The `es` format supports better optimization for compiling. Webpack will use that format if provided. 

You'll see [import statements](https://github.com/patriciogonzalezvivo/glslCanvas/blob/master/dist/GlslCanvas.es.js#L1) at the top of a `es` file.

**Comment by patriciogonzalezvivo** [comment]
I see! Thanks for the clarification. This looks great

**Pull request merged**
