### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by RoryO**
Doing some updating and refactoring work on glslEditor. Babel is locked at 5.8 here causing issues which disallows GlslEditor to update Babel and friends. No major changes, bit of tooling:

- Adds Yarn for deterministic npm module installation
- Updates Babel to most recent
- Updates all other dependencies to most recent
- Removes `window.GlslEditor` assignment. Makes a mess with latest babelify
- Differentiate between release and dev building with NODE_ENV flag
- Moves everything to dev dependencies. Nothing is required at runtime since this is a compiled project.
- Update docs
- Minor version bump

### CODE REVIEW

**Comment by patriciogonzalezvivo** [comment]
Hi! Thanks so much for taking you time to fix this mess. 
Ignorant question... removing `window.glslCanvas` will prevent me to do https://github.com/patriciogonzalezvivo/thebookofshaders/blob/master/src/main.js#L132 ??

**Comment by RoryO** [comment]
The node ecosystem is a mess in general.

Most probably that will not work. The idea of ES6 modules is similar to python modules. They should not alter anything outside of it's scope. It looks like the `main.js` files is fixed by adding `window.GlslCanvas = window.GlslCanvas || GlslCanvas` at the top.

**Comment by giannif** [comment]
@RoryO I have a PR open that builds for the browse as well as node, since we need a build that can run standalone (with dependencies included), like @patriciogonzalezvivo mentioned.

https://github.com/patriciogonzalezvivo/glslCanvas/pull/19

**Comment by RoryO** [comment]
@giannif After fixing this I was going to use Webpack. Rollup is a better idea. I'd favor yours over this one except for two things. Here we switch off of `NODE_ENV` for generating source maps. I still feel removing the assignment to `window` is warranted. We can do that in a separate PR though.

**Comment by giannif** [comment]
@RoryO good catch removing the window assignment, I can remove [this line in my PR](https://github.com/patriciogonzalezvivo/glslCanvas/blob/master/src/GlslCanvas.js#L494), since umd builds will export the name `GlslCanvas` automatically. 

As far as node flags, when would you be running production and when would you not be? If your trying to improve compile time when developing `glslCanvas` then we can have an `npm script dev` command that will run rollup in watch mode, and we can then not minify and do sourcemaps based on the `process.env.ROLLUP_WATCH` value, and also recompile when the src changes.

I've set up a few projects this way since I created the `glslCanvas` PR and can add this easily

**Comment by RoryO** [comment]
Sure, lets do that and document it.

**Comment by giannif** [comment]
@RoryO done, check it out: #19

**Comment by RoryO** [comment]
@patriciogonzalezvivo Lets use #19 instead.

**Comment by patriciogonzalezvivo** [comment]
Thanks you both. JS is not my medium, thanks for taking your time and energy to fix this following my convoluted logic : )

**Comment by patriciogonzalezvivo** [comment]
Hi! I can't build. Maybe you two know what I'm doing wrong:

```
[~/Desktop/glslCanvas]$ yarn run build                               *[master] 
yarn run v1.3.2
$ rollup -c
/bin/sh: rollup: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by patriciogonzalezvivo** [comment]
After doing: `npm install --global rollup`

I get this:

```
yarn run v1.3.2
$ rollup -c
[!] Error: Cannot find module 'rollup-plugin-node-resolve'
Error: Cannot find module 'rollup-plugin-node-resolve'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/patricio/Desktop/glslCanvas/rollup.config.js:5:31)
    at Module._compile (module.js:660:30)
    at Object.require.extensions..js (/usr/local/lib/node_modules/rollup/bin/rollup:20393:19)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by patriciogonzalezvivo** [comment]
Hi @RoryO @giannif I'm trying to re build in yarn and I'm getting this:

```
[~/Desktop/glslCanvas]$ yarn run build                                                                                                               *[master] 
yarn run v1.3.2
$ rollup -c

src/GlslCanvas.js → lib/GlslCanvas.js...
[!] (babel plugin) Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
src/GlslCanvas.js
Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at error (/Users/patricio/Desktop/glslCanvas/node_modules/rollup/dist/rollup.js:185:14)
    at Object.error (/Users/patricio/Desktop/glslCanvas/node_modules/rollup/dist/rollup.js:9469:6)
    at promise.then.previous (/Users/patricio/Desktop/glslCanvas/node_modules/rollup/dist/rollup.js:9478:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Pull request closed without merging**
